# Generated by Django 5.0.1 on 2024-02-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_processor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PdfModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_file", models.FileField(upload_to="pdfs/")),
            ],
        ),
        migrations.DeleteModel(
            name="UploadedFile",
        ),
    ]
